# Using new container infrastructure
sudo: false

dist: trusty

# Using maven
language: java
jdk:
- openjdk16

# Caching for faster builds
cache:
  directories:
  - $HOME/.m2

# Only re-build CraftBukkit/Spigot versions that are missing in the cache
# Add entries here for every required version of CraftBukkit
before_install:
- ./installSpigotDependencies.sh

install: true
script: mvn clean install
