# Using new container infrastructure
sudo: false

# Using maven
language: java
jdk:
- oraclejdk8

# Caching for faster builds
cache:
  directories:
  - $HOME/.m2

# Only re-build craftbukkit/spigot versions that are missing in the cache
# Add entries here for every required version of craftbukkit
before_install:
- if [ ! -f "$HOME/.m2/repository/org/bukkit/craftbukkit/1.14-R0.1-SNAPSHOT/craftbukkit-1.14-R0.1-SNAPSHOT.jar" ]; then ./installSpigot.sh 1.14 ; else echo "Not compiling Spigot 1.14 because it is already in our maven" ; fi

install: true
script: mvn clean install
