# Using new container infrastructure
sudo: false

dist: trusty

# Using maven
language: java
jdk:
- openjdk16

# Caching for faster builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.jabba

# Install missing Spigot dependencies.
before_install:
- ./installSpigotDependencies.sh

install: true
script: mvn clean install
