# This name is also shown in the status badge.
name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Our build scripts already install the required JDK versions themselves.
    #- uses: actions/setup-java@v2
    #  with:
    #    java-version: '16'
    #    distribution: 'adopt'
    - uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
    - uses: actions/cache@v2
      with:
        path: ~/.jabba
        key: ${{ runner.os }}-jabba
    - run: ./build.sh
    # Upload workflow artifacts to allow the inspection of build results.
    # These are only retained for a few days.
    - run: mkdir staging && cp build/*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        path: staging
